# Generated by Django 4.0.1 on 2022-05-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.AlterField(
            model_name='account',
            name='IdNo',
            field=models.IntegerField(default=False, primary_key=True, serialize=False),
        ),
    ]
