# Generated by Django 4.0.1 on 2022-06-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='idno',
            field=models.IntegerField(default=0),
        ),
    ]
