# Generated by Django 4.0.1 on 2022-05-13 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_account_id_alter_account_idno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='IdNo',
            new_name='idno',
        ),
    ]
