# Generated by Django 4.0.1 on 2022-06-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_idno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.AlterField(
            model_name='account',
            name='idno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
