# Generated by Django 4.0.1 on 2022-05-16 05:42

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_idno_account_idno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_No',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
