# Generated by Django 4.0.1 on 2022-06-14 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('school_address', models.CharField(max_length=200)),
                ('academic_level', models.CharField(max_length=100)),
                ('year_of_completion', models.DateField(null=True)),
                ('reason_for_application', models.TextField()),
                ('recomendation', models.FileField(upload_to='recomendation')),
                ('birth_certificate', models.FileField(upload_to='files')),
                ('national_id', models.FileField(upload_to='files')),
                ('sponsor', models.TextField(max_length=200, null=True)),
                ('applicationDate', models.DateField(auto_now_add=True)),
                ('staffapproval', models.TextField(default='Pending review', max_length=20)),
                ('sponsorshipStatus', models.TextField(default='Awaiting Sponsorship', max_length=20)),
                ('idno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
