# Generated by Django 4.0.1 on 2022-04-19 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sponsor',
        ),
    ]
