# Generated by Django 4.0.1 on 2022-05-13 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications',
            old_name='IdNO',
            new_name='IdNo',
        ),
    ]
