# Generated by Django 4.0.1 on 2022-04-25 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_applications_sponid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications',
            old_name='applicationDate',
            new_name='ApplicationDate',
        ),
        migrations.RenameField(
            model_name='applications',
            old_name='sponsorId',
            new_name='SponsorId',
        ),
        migrations.RenameField(
            model_name='applications',
            old_name='sponsorshipStatus',
            new_name='SponsorshipStatus',
        ),
        migrations.RenameField(
            model_name='applications',
            old_name='staffApproval',
            new_name='StaffApproval',
        ),
        migrations.RenameField(
            model_name='applications',
            old_name='studentId',
            new_name='StudentId',
        ),
    ]
