# Generated by Django 4.0.1 on 2022-05-13 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_idno_applications_idno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications',
            old_name='IdNo',
            new_name='idno',
        ),
    ]
