# Generated by Django 4.0.1 on 2022-05-13 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_idno_applications_idno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications',
            old_name='sponsorId',
            new_name='sponsor',
        ),
    ]
