# Generated by Django 4.0.1 on 2022-05-13 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_rename_sponsorid_applications_sponsor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications',
            old_name='staffApproval',
            new_name='staffapproval',
        ),
    ]
