# Generated by Django 4.0.1 on 2022-04-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_rename_sponsorid_applications_sponsorid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='sponsorshipStatus',
            field=models.TextField(default='Awaiting Sponsorship', max_length=20),
        ),
    ]
